maven_version: 3.2.5

# path for ansible to store downloaded or templated data
data_path: '/data/tools'

# Maven settings
maven_filename: "apache-maven-{{ maven_version }}-bin.tar.gz"
maven_bin_path: '/usr/local/bin'

# base installation directory for any Maven distribution
maven_install_dir: '/opt/maven'

